<?php

namespace app\models;

use app\models\base\PropertyBase;
use yii\helpers\ArrayHelper;

class Property extends PropertyBase
{
    public $imageUrls = [];

    public function rules()
    {
        return ArrayHelper::merge(parent::rules(), [
            ['imageUrls', 'safe',]
        ]);
        return parent::rules(); // TODO: Change the autogenerated stub
    }

    public function beforeDelete()
    {
        foreach ($this->propertyImages as $image)
        {
            $image->delete();
        }

        foreach ($this->appointments as $appointment)
        {
            $appointment->delete();
        }

        return parent::beforeDelete();
    }

    public function afterSave($insert, $changedAttributes)
    {
        if ($this->imageUrls)
        {
            PropertyImage::deleteAll(['property_id' => $this->id]);
            foreach ($this->imageUrls as $image)
            {
                PropertyImage::create($this->id, $image);
            }
        }


        return parent::afterSave($insert, $changedAttributes);
    }
}